name: Build Docs and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        
      - name: Install and Build 🔧
        run: |
          sudo apt-get install python3-setuptools
          pip3 install mkdocs mkdocs-material
          export PATH=~/.local/bin:$PATH
          make docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: html
